version: "3.5"

services:
    httpd:
        build:
            context: "./images/httpd"
        container_name: "akaunting-httpd"
        depends_on:
            - "php-fpm"
        networks:
            - "akaunting_network"
        ports:
            - "9080:9080"
            - "9443:9443"
        volumes:
            - "shared:/shared" # allow to use the php-fpm socket
            - "./logs/httpd:/var/log/httpd:delegated"
            - "./resources/certificates:/certificates:cached"
            - "./resources/usr/local/apache2/conf.d:/usr/local/apache2/conf.d:cached"
            - "../:/srv/akaunting-repositories:cached"

    nginx:
        build:
            context: "./images/nginx"
        # Transform the template into an actual file
        command: /bin/bash -c "envsubst < /etc/nginx/fastcgi.conf.tpl > /etc/nginx/fastcgi.conf && nginx -g 'daemon off;'"
        container_name: "nginx"
        depends_on:
            - "php-fpm"
        environment:
            - "DOLLAR=$$"
            - "FASTCGI_SPLIT_PATH_INFO=${EXAMPLE_DOCKER_FASTCGI_SPLIT_PATH_INFO}"
            - "FASTCGI_INTERCEPT_ERRORS=${EXAMPLE_DOCKER_FASTCGI_INTERCEPT_ERRORS}"
            - "FASTCGI_IGNORE_CLIENT_ABORT=${EXAMPLE_DOCKER_FASTCGI_IGNORE_CLIENT_ABORT}"
            - "FASTCGI_CONNECT_TIMEOUT=${EXAMPLE_DOCKER_FASTCGI_CONNECT_TIMEOUT}"
            - "FASTCGI_SEND_TIMEOUT=${EXAMPLE_DOCKER_FASTCGI_SEND_TIMEOUT}"
            - "FASTCGI_READ_TIMEOUT=${EXAMPLE_DOCKER_FASTCGI_READ_TIMEOUT}"
            - "FASTCGI_BUFFER_SIZE=${EXAMPLE_DOCKER_FASTCGI_BUFFER_SIZE}"
            - "FASTCGI_BUFFERS=${EXAMPLE_DOCKER_FASTCGI_BUFFERS}"
            - "FASTCGI_BUSY_BUFFERS_SIZE=${EXAMPLE_DOCKER_FASTCGI_BUSY_BUFFERS_SIZE}"
            - "FASTCGI_TEMP_FILE_WRITE_SIZE=${EXAMPLE_DOCKER_FASTCGI_TEMP_FILE_WRITE_SIZE}"
        networks:
            akaunting_network:
                aliases: # Allows (sso|dev).akaunting.localhost to be resolved internally from php-fpm
                    - "api.akaunting.localhost"
                    - "dev.akaunting.localhost"
                    - "akaunting.dev"
                    - "akaunting.test"
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - "shared:/shared" # allow to use the php-fpm socket
            - "./logs/nginx:/var/log/nginx:delegated"
            - "./resources/certificates:/certificates:cached"
            - "./resources/etc/nginx/conf.d:/etc/nginx/conf.d:cached"
            - "./resources/etc/nginx/sites-available:/etc/nginx/sites-available:cached"
            - "./resources/etc/nginx/sites-enabled:/etc/nginx/sites-enabled:cached"
            - "../:/srv/akaunting-repositories:cached"

    # Don't forget to update docker-compose.unit-test.yml
    php-fpm:
        build:
            context: "./images/php-fpm"
        container_name: "php-fpm"
        environment:
            - "PHP_INI_SCAN_DIR=:/usr/local/etc/php/custom.conf.d" # Allow users to override configs
            - "TEST_BASEURL"
            - "TEST_DB_HOST"
            - "TEST_DB_NAME"
            - "TEST_DB_USER"
            - "TEST_DB_PASSWORD"
        networks:
            - "akaunting_network"
        volumes:
            - "shared:/shared" # expose php-fpm socket
            - "./logs/php-fpm:/var/log/php-fpm:delegated"
            - "./resources/certificates:/usr/local/share/ca-certificates:cached" # Mount extra certificates
            - "./resources/sphinx:/sphinx:cached" # expose sphinx API. We have to do this here because we need to be enable to update the plugin before we can start the container.
            - "./resources/usr/local/etc/php/conf.d:/usr/local/etc/php/custom.conf.d:cached"
            - "../:/srv/akaunting-repositories:delegated"

volumes:
    shared:

networks:
    akaunting_network:
        driver: "bridge"
        name: "akaunting_network"
